---
- name: Gather videobridge and jibri facts
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['jitsi_videobridge'] | union(groups['jibri'])}}"

- include_tasks: preconfigure.yml

- name: Install apt packages required for Jitsi
  apt:
    name:
      - openjdk-8-jre-headless
      - lua5.1
      - prosody
    autoremove: true

- include_tasks: create_certificates.yml
- include_tasks: prosody.yml

- name: Configure jitsi-meet
  template:
    src: jitsi-meet-config.js
    dest: /etc/jitsi/meet/{{ jitsi_fqdn }}-config.js

- name: Configure nginx for jitsi-meet
  template:
    src: jitsi-meet.nginx.conf
    dest: /etc/nginx/snippets/{{ jitsi_fqdn }}/jitsi-meet.conf
  notify: Reload nginx

- name: Add application/wasm to mime.types
  lineinfile:
    path: /etc/nginx/mime.types
    regexp: '^application/wasm'
    line: 'application/wasm wasm;'
    insertbefore: '^}'
    create: no
  notify: Reload nginx

- name: Configure jicofo
  template:
    src: jicofo.conf
    dest: /etc/jitsi/jicofo/jicofo.conf
  notify: Restart jicofo
