---
- name: Preconfigure Jicofo XMPP username
  debconf:
    name: jicofo
    question: jicofo/jicofo-authuser
    vtype: string
    value: focus
  changed_when: False

- name: Preconfigure Jicofo XMPP password
  debconf:
    name: jicofo
    question: jicofo/jicofo-authpassword
    vtype: password
    value: "{{ jicofo_password }}"
  changed_when: False

- name: Preconfigure Jicofo component secret
  debconf:
    name: jicofo
    question: jicofo/jicofosecret
    vtype: password
    value: "{{ jicofo_secret }}"
  changed_when: False

## This is used *too* by jitsi-meet-web-config.postinst
- name: Preconfigure jitsi-videobridge
  debconf:
    name: jitsi-videobridge
    question: jitsi-videobridge/jvb-hostname
    vtype: string
    value: "{{ ansible_fqdn }}"

## And this by /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
- name: Preconfigure Jitsi Meet
  debconf:
    name: jitsi-meet
    question: jitsi-meet/jvb-hostname
    vtype: string
    value: "{{ ansible_fqdn }}"

## Used by jitsi-meet-turnserver
- name: Set up turn server secret
  debconf:
    name: jitsi-meet-prosody
    question: jitsi-meet-prosody/turn-secret
    vtype: password
    value: "{{ turn_secret }}"
  when: turn_enabled is defined and turn_enabled
