---

- name: Restart jicofo
  service:
    name: jicofo
    state: restarted

- name: Restart prosody
  service:
    name: prosody
    state: restarted

- name: Restart saslauthd
  service:
    name: saslauthd
    state: restarted
